apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-operators
spec:
  devWorkspace:
    enable: true
  metrics:
    enable: true
  server:
    cheClusterRoles: ''
    cheWorkspaceClusterRole: ''
    gitSelfSignedCert: false
    nonProxyHosts: ''
    proxyPort: ''
    proxySecret: ''
    proxyURL: ''
    workspaceNamespaceDefault: <username>-devspaces
  auth:
    identityProviderURL: ''
    oAuthClientName: ''
    oAuthSecret: ''
  database:
    chePostgresDb: ''
    chePostgresHostName: ''
    chePostgresPort: ''
    chePostgresSecret: ''
    externalDb: false
  storage:
    postgresPVCStorageClassName: ''
    preCreateSubPaths: true
    pvcClaimSize: 10Gi
    pvcStrategy: common
    workspacePVCStorageClassName: ''
