---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-namespace-admin
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-namespace-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-namespace-admin
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: demo-cicd